# Generated by Django 5.0 on 2024-03-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rating', models.FloatField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('budget', models.IntegerField(null=True)),
            ],
        ),
    ]
